version: "3.8"
services:
    # Laravel Application
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        environment:
            - APP_NAME=eBrew Café
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=ebrew_laravel
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - SESSION_DRIVER=database
            - CACHE_DRIVER=database
            - QUEUE_CONNECTION=database
        volumes:
            - ./storage:/var/www/html/storage
        depends_on:
            - database
        networks:
            - ebrew-network

    # MySQL Database
    database:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=ebrew_laravel
            - MYSQL_USER=ebrew_user
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ebrew-network

    # Redis Cache (Optional)
    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        networks:
            - ebrew-network

volumes:
    mysql_data:

networks:
    ebrew-network:
        driver: bridge
