[phases.setup]
nixPkgs = ["php82Extensions.mongodb"]

[phases.install]
cmds = ["install-php-extensions mongodb"]

[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-interaction",
  "npm ci --only=production",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache", 
  "php artisan view:cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public/"