[build]
builder = "nixpacks"

[build.env]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[build.install]
cmd = """
apt-get update && 
apt-get install -y php8.2-fpm php8.2-cli php8.2-mysql php8.2-xml php8.2-curl php8.2-mbstring php8.2-zip php8.2-gd
"""

[deploy]
startCommand = "vendor/bin/heroku-php-apache2 public/"
healthcheckPath = "/"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"