[build]
builder = "nixpacks"

[build.env]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[deploy]
startCommand = "vendor/bin/heroku-php-apache2 public/"
healthcheckPath = "/"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
SESSION_DRIVER = "database"
CACHE_DRIVER = "database"
QUEUE_CONNECTION = "database"