[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"
startCommand = "entrypoint.sh"

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_LEVEL = "info"