[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "always"
startCommand = "bash /usr/local/bin/entrypoint.sh"

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "true"
APP_URL = "https://ebrewlaravel-copy-production.up.railway.app"
DB_CONNECTION = "mysql"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_DATABASE = "railway"
DB_USERNAME = "root"
DB_PASSWORD = "LlvoGAKttnOCmRkXQDSbPPYKUgYWZajz"
DATABASE_URL = "mysql://root:LlvoGAKttnOCmRkXQDSbPPYKUgYWZajz@mysql.railway.internal:3306/railway"
SESSION_DRIVER = "file"
SESSION_SECURE_COOKIE = "true"
SESSION_SAME_SITE = "lax"