[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health.php"
healthcheckTimeout = 120
restartPolicyType = "always"

[environments.production.variables]
APP_ENV = "production"
APP_DEBUG = "false"