services:
  - type: web
    name: ebrew-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install && npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: mysql
    healthCheckPath: /
    
databases:
  - name: ebrew-mysql
    databaseName: ebrew_cafe
    user: ebrew_user
    plan: free